# -*- coding: utf-8 -*-
{
    'name': 'Dynamic Reports',
    'version': '16.0.1.0.1',
    'summary': '',
    'category': '',
    'author': 'Cybrosys Techno solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['web_digital_sign','sale_management', 'purchase', 'account', 'kefah_power','crm'],
    'data': [
        'data/paper_format.xml',
        'views/sale_order.xml',
        'views/purchase_order.xml',
        'views/account_move.xml',
        'views/company.xml',
        'views/company_data_template.xml',
        'report/sale_order_report.xml',
        'report/purchase_order_report.xml',
        'report/invoice_report.xml',
        'report/print_report.xml',
        'data/sale_mail_data.xml',
        'data/purchase_mail_data.xml',
        'data/account_mail_data.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
